### ISSUE TITLE
Unable to run any exemple

### ISSUE THREAD

**Issue by vincentditlevinz** [metal/metal-examples#4]
Except "hello world", I am unable to obtain a runnable demo from any example. For instance, I build "modal nested component" example according to the readme and see this in Chrome console:
```
Uncaught Error: No template with namespace "CloseHeader.incrementaldom" has been loaded yet.
    at Modal.js:1838
    at $render (Modal.js:4009)
    at Soy.renderIncDom (Modal.js:1924)
    at render (Modal.js:3124)
    at Modal.js:15130
    at f (Modal.js:15094)
    at callPatch_ (Modal.js:16183)
    at tryPatchWithNoParent_ (Modal.js:16238)
    at patch (Modal.js:16202)
    at Soy.patch (Modal.js:2177)
```

On the other hand, the same (almost) example works well when I download it from the web site (boilerplate.zip) and build it according to the readme.
I use npm 3.10.10 and node 6.11.2 on windows 10

**Comment by vbence86** [comment]
@vincentditlevinz Thanks for the detailed description of this issue. I'm looking into it now.

**Comment by vbence86** [comment]
@vincentditlevinz the PR above fixes the reported issue. We also updated the archive on metaljs.com. Thanks for reporting this.
